// <auto-generated />
using System;
using EstateFlow.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstateFlow.Server.Migrations
{
    [DbContext(typeof(EstateFlowDbContext))]
    [Migration("20260926183543_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstateFlow.Server.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Budapest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Debrecen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Szeged"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kecskemét"
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdvertisementText")
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Address = "1068 Budapest, Szondi utca 45.",
                            AdvertisementText = "Világos, felújított másfél szobás lakás a VI. kerület szív",
                            CityId = 1,
                            Code = "BPSZK",
                            Name = "Szondi utcai lakás",
                            SquareMeters = 54
                        },
                        new
                        {
                            Id = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            Address = "1092 Budapest, Ferenc körút 12.",
                            CityId = 1,
                            Code = "BPFKR",
                            Name = "Ferenc körúti lakás",
                            SquareMeters = 68
                        },
                        new
                        {
                            Id = new Guid("9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d"),
                            Address = "4026 Debrecen, Egyetem sugárút 8.",
                            AdvertisementText = "Hangulatos, erkélyes lakás a Nagyerdő közelében, egyetemis",
                            CityId = 2,
                            Code = "DEEGY",
                            Name = "Egyetem sugárúti lakás",
                            SquareMeters = 47
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            FilePath = "uploads/properties/bpszk-nappali.jpg",
                            Name = "Nappali",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            UploadedAt = new DateTime(2026, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6ec0bd7f-11c0-43da-975e-2a8ad9ebae0b"),
                            FilePath = "uploads/properties/bpszk-haloszoba.jpg",
                            Name = "Hálószoba",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            UploadedAt = new DateTime(2026, 1, 15, 10, 32, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f9168c5e-ceb2-4faa-b6bf-329bf39fa1e4"),
                            FilePath = "uploads/properties/bpfkr-homlokzat.jpg",
                            Name = "Utcai homlokzat",
                            PropertyId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            UploadedAt = new DateTime(2026, 2, 3, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d2719b1e-1c3b-4e5f-9a6d-8b7c6d5e4f3a"),
                            FilePath = "uploads/properties/deegy-konyha.jpg",
                            Name = "Konyha",
                            PropertyId = new Guid("9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d"),
                            UploadedAt = new DateTime(2026, 2, 10, 9, 15, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.PropertyImage", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
