// <auto-generated />
using System;
using EstateFlow.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstateFlow.Server.Migrations
{
    [DbContext(typeof(EstateFlowDbContext))]
    [Migration("20261004080545_AddInvoiceAndContract")]
    partial class AddInvoiceAndContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstateFlow.Server.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Budapest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Debrecen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Szeged"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kecskemét"
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("ReadingPeriod")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("UtilityTypeId");

                    b.ToTable("Meters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3301"),
                            Location = "előszobai szekrényben",
                            Name = "Villanyóra",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            ProviderId = 1,
                            ReadingPeriod = "minden hónap elején",
                            SerialNumber = "EL-2019-448723",
                            UtilityTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3302"),
                            Location = "konyhában a bejárati ajtó mellett",
                            Name = "Gázóra",
                            Note = "2027-ben hitelesítés esedékes",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            ProviderId = 2,
                            SerialNumber = "GA-2017-902211",
                            UtilityTypeId = 2
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            Location = "fürdőszobában a kád alatt",
                            Name = "Vízóra",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            ProviderId = 3,
                            ReadingPeriod = "minden páros hónapban van leolvasás",
                            SerialNumber = "VZ-2021-115847",
                            UtilityTypeId = 3
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3304"),
                            Location = "folyosón a bejárati ajtó mellett",
                            Name = "Villanyóra",
                            PropertyId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            ProviderId = 1,
                            ReadingPeriod = "minden hónap elején",
                            SerialNumber = "EL-2020-771139",
                            UtilityTypeId = 1
                        },
                        new
                        {
                            Id = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3305"),
                            Location = "konyhában a mosogató alatt",
                            Name = "Vízóra",
                            PropertyId = new Guid("9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d"),
                            ProviderId = 4,
                            SerialNumber = "VZ-2018-660254",
                            UtilityTypeId = 3
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.MeterReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.ToTable("MetersReading");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d4d4e51-6d1a-4c62-a1f8-58a0e0a4c001"),
                            ApprovedAt = new DateTime(2026, 3, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            MeasuredAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            MeterId = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3301"),
                            PhotoPath = "uploads/readings/bpszk-villany-2026-03.jpg",
                            ReportedAt = new DateTime(2026, 3, 1, 8, 5, 0, 0, DateTimeKind.Utc),
                            Value = 12450m
                        },
                        new
                        {
                            Id = new Guid("8d4d4e51-6d1a-4c62-a1f8-58a0e0a4c002"),
                            ApprovedAt = new DateTime(2026, 4, 2, 10, 15, 0, 0, DateTimeKind.Utc),
                            MeasuredAt = new DateTime(2026, 4, 1, 7, 40, 0, 0, DateTimeKind.Utc),
                            MeterId = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3301"),
                            PhotoPath = "uploads/readings/bpszk-villany-2026-04.jpg",
                            ReportedAt = new DateTime(2026, 4, 1, 7, 45, 0, 0, DateTimeKind.Utc),
                            Value = 12588m
                        },
                        new
                        {
                            Id = new Guid("8d4d4e51-6d1a-4c62-a1f8-58a0e0a4c003"),
                            ApprovedAt = new DateTime(2026, 5, 4, 8, 30, 0, 0, DateTimeKind.Utc),
                            MeasuredAt = new DateTime(2026, 5, 1, 9, 30, 0, 0, DateTimeKind.Utc),
                            MeterId = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3301"),
                            ReportedAt = new DateTime(2026, 5, 3, 18, 20, 0, 0, DateTimeKind.Utc),
                            Value = 12731m
                        },
                        new
                        {
                            Id = new Guid("8d4d4e51-6d1a-4c62-a1f8-58a0e0a4c004"),
                            MeasuredAt = new DateTime(2026, 6, 1, 8, 10, 0, 0, DateTimeKind.Utc),
                            MeterId = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3301"),
                            PhotoPath = "uploads/readings/bpszk-villany-2026-06.jpg",
                            ReportedAt = new DateTime(2026, 6, 1, 9, 10, 0, 0, DateTimeKind.Utc),
                            Value = 12876m
                        },
                        new
                        {
                            Id = new Guid("8d4d4e51-6d1a-4c62-a1f8-58a0e0a4c005"),
                            ApprovedAt = new DateTime(2026, 4, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            MeasuredAt = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MeterId = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            PhotoPath = "uploads/readings/bpszk-viz-2026-04.jpg",
                            ReportedAt = new DateTime(2026, 4, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            Value = 341.605m
                        },
                        new
                        {
                            Id = new Guid("8d4d4e51-6d1a-4c62-a1f8-58a0e0a4c006"),
                            MeasuredAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MeterId = new Guid("3f2504e0-4f89-41d3-9a0c-0305e82c3303"),
                            PhotoPath = "uploads/readings/bpszk-viz-2026-06.jpg",
                            ReportedAt = new DateTime(2026, 6, 2, 16, 45, 0, 0, DateTimeKind.Utc),
                            Value = 348.112m
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdvertisementText")
                        .HasColumnType("text");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            Address = "1068 Budapest, Szondi utca 45.",
                            AdvertisementText = "Világos, felújított másfél szobás lakás a VI. kerület szívében",
                            CityId = 1,
                            Code = "BPSZK",
                            Name = "Szondi utcai lakás",
                            SquareMeters = 54
                        },
                        new
                        {
                            Id = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            Address = "1092 Budapest, Ferenc körút 12.",
                            CityId = 1,
                            Code = "BPFKR",
                            Name = "Ferenc körúti lakás",
                            SquareMeters = 68
                        },
                        new
                        {
                            Id = new Guid("9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d"),
                            Address = "4026 Debrecen, Egyetem sugárút 8.",
                            AdvertisementText = "Hangulatos, erkélyes lakás a Nagyerdő közelében, egyetemis",
                            CityId = 2,
                            Code = "DEEGY",
                            Name = "Egyetem sugárúti lakás",
                            SquareMeters = 47
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.PropertyImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            FilePath = "uploads/properties/bpszk-nappali.jpg",
                            Name = "Nappali",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            UploadedAt = new DateTime(2026, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6ec0bd7f-11c0-43da-975e-2a8ad9ebae0b"),
                            FilePath = "uploads/properties/bpszk-haloszoba.jpg",
                            Name = "Hálószoba",
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            UploadedAt = new DateTime(2026, 1, 15, 10, 32, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f9168c5e-ceb2-4faa-b6bf-329bf39fa1e4"),
                            FilePath = "uploads/properties/bpfkr-homlokzat.jpg",
                            Name = "Utcai homlokzat",
                            PropertyId = new Guid("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
                            UploadedAt = new DateTime(2026, 2, 3, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d2719b1e-1c3b-4e5f-9a6d-8b7c6d5e4f3a"),
                            FilePath = "uploads/properties/deegy-konyha.jpg",
                            Name = "Konyha",
                            PropertyId = new Guid("9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d"),
                            UploadedAt = new DateTime(2026, 2, 10, 9, 15, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("UtilityTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilityTypeId");

                    b.ToTable("Provider");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MVM Next",
                            UtilityTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "FŐGÁZ",
                            Note = "a gázórákat évente egyszer olvassák",
                            UtilityTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fővárosi Vízművek",
                            UtilityTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Debreceni Vízmű",
                            UtilityTypeId = 3
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TenantId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b28a2f0-762c-4b7f-8b3e-9a5d1c4e6f01"),
                            MonthlyRent = 240000m,
                            PropertyId = new Guid("0f8fad5b-d9cb-469f-a165-70867728950e"),
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("c56a4180-65aa-42ec-a945-5fd21dec0538")
                        },
                        new
                        {
                            Id = new Guid("0b28a2f0-762c-4b7f-8b3e-9a5d1c4e6f02"),
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonthlyRent = 150000m,
                            PropertyId = new Guid("9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d"),
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TenantId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479")
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c56a4180-65aa-42ec-a945-5fd21dec0538"),
                            Email = "kovacs.anna@example.com",
                            FirstName = "Anna",
                            LastName = "Kovács",
                            PhoneNumber = "+36 20 123 4567"
                        },
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Email = "szabo.peter@example.com",
                            FirstName = "Péter",
                            LastName = "Szabó"
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.UtilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UtilityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electricity"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Water"
                        });
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Contract", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstateFlow.Server.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Invoice", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstateFlow.Server.Domain.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Meter", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany("Meters")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstateFlow.Server.Domain.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstateFlow.Server.Domain.UtilityType", "UtilityType")
                        .WithMany()
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Provider");

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.MeterReading", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Meter", "Meter")
                        .WithMany("Readings")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.PropertyImage", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Provider", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.UtilityType", "UtilityType")
                        .WithMany("Providers")
                        .HasForeignKey("UtilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UtilityType");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Rental", b =>
                {
                    b.HasOne("EstateFlow.Server.Domain.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstateFlow.Server.Domain.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Meter", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.Property", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Meters");
                });

            modelBuilder.Entity("EstateFlow.Server.Domain.UtilityType", b =>
                {
                    b.Navigation("Providers");
                });
#pragma warning restore 612, 618
        }
    }
}
